{"name": "Неудачный вход в систему для существующего пользователя с неверными данными", "status": "passed", "steps": [{"name": "Авторизация пользователя", "status": "passed", "parameters": [{"name": "user_login_data_json", "value": "{'email': 'nibpogzmcz@yandex.ru', 'password': 'INc0RR3CT_P@ssWORD777'}"}], "start": 1736340092208, "stop": 1736340092471}], "parameters": [{"name": "field_name", "value": "'password'"}, {"name": "field_value", "value": "'INc0RR3CT_P@ssWORD777'"}], "start": 1736340092208, "stop": 1736340092471, "uuid": "88f4eb51-520e-464f-9a49-9ac7d7c08c01", "historyId": "7ce1b67fd76eda6c3ac1cd760f9d3d0a", "testCaseId": "88a6f8856dc37b2b144fff9c955f564b", "fullName": "tests.auth.test_user_login.TestUserLogin#test_login_by_existing_user_with_incorrect_data_returns_error", "labels": [{"name": "parentSuite", "value": "tests.auth"}, {"name": "suite", "value": "test_user_login"}, {"name": "subSuite", "value": "TestUserLogin"}, {"name": "host", "value": "DESKTOP-2S7589E"}, {"name": "thread", "value": "2324-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.auth.test_user_login"}]}